### ISSUE TITLE
Docusaurus nits

### ISSUE THREAD

**Issue by divya-mohan0209** [kubewarden/docs#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Issue opened to track nits mentioned by @ereslibre in [this comment](https://github.com/kubewarden/docs/pull/104#pullrequestreview-964265371) on the PR #104 

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by flavio** [comment]
Temporarily blocked because @divya-mohan0209 is busy with KubeCon and travels

**Comment by flavio** [comment]
@divya-mohan0209 I've addressed the issues while working on the changes I've done to the Go SDK. I'll open a PR ASAP. In the meantime, don't waste your time on that

**Comment by flavio** [comment]
We can close this one, all the changes have been merged and deployed now
