### ISSUE TITLE
Document architecture

### ISSUE THREAD

**Issue by flavio** [kubewarden/docs#13]
## Acceptance criteria

* Explain the components of the Kubewarden stack
* Explain the relation between all the components
* Describe the flow of an incoming request: what are the components it goes through

**Comment by ereslibre** [comment]
Submitted draft PR https://github.com/kubewarden/docs/pull/24 for early feedback, so we can sync on this. I'm not yet done with it, but I'd like to know your opinion on verbosity, style...
