### ISSUE TITLE
Initial example fails

### ISSUE THREAD

**Issue by kkaempf** [kubewarden/docs#17]
> &gt; helm repo add kubewarden https://charts.kubewarden.io
> "kubewarden" has been added to your repositories
> &gt; helm install --namespace kubewarden --create-namespace kubewarden-controller kubewarden/kubewarden-controller
> Installing chart "kubewarden-controller" in namespace "kubewarden"…
> Done! 👏 
> &gt; kubectl apply -f - <<EOF
> &gt; apiVersion: kubewarden.io/v1alpha1
> &gt; kind: ClusterAdmissionPolicy
> &gt; metadata:
> &gt;   name: privileged-pods
> &gt; spec:
> &gt;   module: registry://ghcr.io/kubewarden/policies/pod-privileged:v0.1.1
> &gt;   resources:
> &gt;   - pods
> &gt;   operations:
> &gt;   - CREATE
> &gt;   - UPDATE
> &gt; EOF
> error: unable to recognize "STDIN": no matches for kind "ClusterAdmissionPolicy" in version "kubewarden.io/v1alpha1"

**Comment by kkaempf** [comment]
Same error if I use `registry://ghcr.io/kubewarden/policies/pod-privileged:v0.1.4`

**Comment by kkaempf** [comment]
Oh, kubewarden-controller is in `ImagePullBackOff`

**Comment by flavio** [comment]
The docs were outdated (the fix from above solves that), plus the helm chart had some issues too. I've already pushed all the fixes to the helm chart, once the PR from above is merged you can go ahead and try again.

This time it will work, I just tried that on a brand new cluster.

**Comment by flavio** [comment]
> Oh, kubewarden-controller is in `ImagePullBackOff`

Ensure you refresh the helm chart repo locally to have the latest fixes: `helm repo update`

Also make sure you remove the previous helm installation of kubewarden via `helm uninstall`

**Comment by kkaempf** [comment]
Now I fail at

> kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io

with

> No resources found in default namespace.

**Comment by kkaempf** [comment]
> kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io -n kubewarden

is better

**Comment by kkaempf** [comment]
Confirmed fixed
