### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/docs#21]
Creating this issue to discuss the big picture structure of the docs:

1. **Introduction**
1. **Quick start**
1. **Writing policies**
    1. **Introduction**: here we could talk a bit about what a language needs to have to write policies with it, the waPC contract (functions, arguments and return structure)
    1. **Supported languages**
        3.2.1. **Rust**
        3.2.2. **TinyGo**: _characteristics, limitations as opposed to Go, and why Go is not an option right now_
        3.2.3. **AssemblyScript**: _characteristics, limitations_
1. **Distributing policies**
1. **Testing policies**
    1. **While developing** a policy
        1. _Use unit tests, integration... whatever you are used to_
        1. _Use the policy-testdrive project for offline tests: how you can run tests that take different settings, and requests checking the response of your policy on a Wasm build of the code you are developing_
    1. **Before deploying** a policy
        1. Use the policy-testdrive project for offline tests: _how you can run tests to understand how it would impact your cluster before the real deployment of your policy coming from a registry/HTTP server_

**Comment by ereslibre** [comment]
cc/ @flavio @kkaempf

**Comment by kkaempf** [comment]
:+1: in general.

I'd still like to see a "5 mins quick start" at the very beginning.
Maybe an "About Kubernetes policies" to generally explain about policies, what they do, etc. ?!
