### ISSUE TITLE
Simple developer workflow

### ISSUE THREAD

**Issue by kkaempf** [kubewarden/docs#30]
While policy generation is [well documented](https://docs.kubewarden.io/writing-policies/rust/02-create-policy.html), getting this policy to run and tested is a spread [over](https://docs.kubewarden.io/writing-policies/rust/06-build-and-distribute.html) [multiple](https://docs.kubewarden.io/distributing-policies.html) [documents](https://docs.kubewarden.io/testing-policies/01-intro.html)

I'd like to see a simple developer workflow, ideally documented on a single page

- [ ] create policy
- [ ] build policy
- [ ] install policy
- [ ] call policy

It's not about writing/testing a _correct_ policy, it's about getting this workflow documented and to give a developer an initial _sense of accomplishment_.

Bonus points if this all can be done on a local workstation (with e.g. k3s) and doesn't need a registry,

**Comment by ereslibre** [comment]
We could have a "Developer Quickstart" section on the book.

**Comment by flavio** [comment]
This can be closed now
