### ISSUE TITLE
Setup canonical links

### ISSUE THREAD

**Issue by jhkrug** [kubewarden/docs#325]
Since we are now using versioned docs we should also be using canonical links so that search results returned by search engines by default direct to the current, canonical pages.

## Acceptance Criteria

- [x] #358 - Markdown files have a canonical link inserted after the front-matter, for example: 

    all of `docs/quick-start.md` and `versioned_docs/version-1.*/quick-start.md` have

    ```html
    <head>
      <link rel="canonical" href="https://docs.kubewarden.io/quick-start"/>
    </head>
    ```

**Comment by jhkrug** [comment]
Best to wait until after the go tutorial is merged then refresh the baseline and check again, due to all the file renames.

**Comment by jhkrug** [comment]
Running up against a problem where Docusaurus builds 01-x.md and 02-y.md to x.html and y.html. I think this sort of usage of numbering for ordering might be quite rare in our docs repos generally which is why the tool used to adjust docs and insert canonical links doesn't cope with it.

**Comment by flavio** [comment]
> Running up against a problem where Docusaurus builds 01-x.md and 02-y.md to x.html and y.html. I think this sort of usage of numbering for ordering might be quite rare in our docs repos generally which is why the tool used to adjust docs and insert canonical links doesn't cope with it.

I'm fine renaming our files if that fixes the problem

**Comment by jhkrug** [comment]
Getting closer, but only worth doing when the docs reorganization is done and files have moved around.

**Comment by jhkrug** [comment]
Completed with #358
