### ISSUE TITLE
Decide on a new docs/Sidebar layout

### ISSUE THREAD

**Issue by kravciak** [kubewarden/docs#332]
Based on our call I created draft of menu that would make sense to me.

```
- What is Kubewarden? (rename from "Introduction")

- Getting Started
  - Overview (main components from Tutorials -> QuickStart)
  - Install & Upgrade
    - Install Kubewarden stack
    - Deploy policies (default PolicyServer, recommended policies, mention ArtifactHub)
    - Supported Upgrade path
    - Other methods
      - Fleet
      - AirGap
      - Without Kubernetes (Raw)

- How-to Guides
  - Operators
    - Using policies (create policy, monitor -> protect mode)
    - Configuration
      - Configure Policies
      - Configure Policy Server
        - Using custom CA
        - Using private registries
      - Telemetry
    - Audit Scanner
    - UI Extension
    - Airgap (remove, move to installation)
 
  - Developers
    - Writing policies
      - Rust, Rego, ...
    - Testing policies
    - Publishing policies
      - ArtifactHub
 
  - Advanced topics
    - Kwctl
    - Policies (could be in How-to -> )
      - Mutating policies
      - Context aware
      - Raw policies
    - Security
      - Secure supply chain
      - Custom certificate authorities
      - Verifying Kubewarden
    - PSP migration

- Reference Guides (split KW vs * comparison and other non-reference into new section)
  - CRDs
  - Architecture
  - Dependency matrix
  - KW vs OPA Gatekeeper
  - KW vs NeuVector (add here?)
  - remove Thread model (move to Advanced topics -> Security -> Thread model)
  - remove OCI registry support (move to How-to -> Developers -> Publishing policies)?
  - remove Operator Manual (move to How-to -> Operators)
  - remove Rancher UI Extension (move to How-to -> UI Extension)
  - remove Airgap (move to Getting Started -> Installation -> Airgap)
  - remove Monitor mode (move to Howto -> Operators -> Using Policies)
  - remove Fleet (move to Getting Started -> Installation -> Fleet)
  - remove Upgrade path (move to Getting Started -> Installation & Upgrades -> Upgrade path)
  - remove Policy evaluation timeout (move to HowTo -> Operators -> Configuration -> Policy evaluation timeout)

- Tutorials (remove whole section)
  - Quick start (move to Getting Started -> Overview)
  - Common tasks (move to How-to -> Advanced topics -> kwctl)
  - Writing policies (move to How-to -> Developers -> Writing policies)
  - Testing policies (move to How-to -> Advanced topics -> kwctl),  rename from "testing" - it sounds like QA work
  - Publish policies to Artifact Hub (move to How-to -> Developers -> Publish policies)
  - Verifying Kubewarden (move to How-to -> Advanced topics -> Security)

- Explanations (remove whole section)
  - Mutating policies (move to How-to -> Advanced topics -> Policies)
  - Distributing policies (move to How-to -> Developers -> Publishing policies)
  - Context aware policies (move to How-to -> Advanced topics -> Policies)
  - Comparisons (move to Reference KW vs ...)
  - Audit Scanner (move to How-to -> Operators -> Audit Scanner)
```

**Comment by jhkrug** [comment]
Thanks @kravciak, a great start. @kubewarden/kubewarden-developers please add comments/thoughts/contributions.

**Comment by viccuad** [comment]
Thanks for giving this a loop!
My 2 cents (wow is this difficult).

I wouldn't remove Tutorials and Explanations, but keep within the Divio system.
Diataxis may not be perfect, but that way we don't need to think and iterate on
the docs structure.

I would make the How-Tos the one separated in Persona sections:

```
- How-tos
  - Operators
    - Installation & upgrade
      - Helm
      - Fleet
      - Airgap
    - Configuring Policies (create policy, monitor -> protect mode)
    - Configuring Policy Servers
      - Using custom CA
      - Using private registries
    - Telemetry
    - Audit Scanner & PolicyReports
    - UI Extension
    - Verifying Kubewarden
  - Policy users
    - Obtaining policies
    - Testing policies
  - Policy authors
    - Writing policies
    - Publishing policies
```

I would keep Tutorials as a way to learn about Kubewarden aspects.
They help when you don't even know what's possible with Kubewarden.

```
- Tutorials:
  - Quickstart
  - Using kwctl
  - Deploying mutating, context-aware policies
  - Using PolicyReports (for the future)
```


I would make Explanations more dry, without steps. If there are a lot of steps
that don't explain, it's a How-To. Link more to Explanations from other pages in the future.

```
- Explanations:
  - Mutating policies
  - Context aware policies
  - Comparisons
  - Audit scanner limitations
```

I would start with the Reference guides as low hanging fruit and try to flatten it:

```
Reference guides:
- Reference Guides
  - CRDs
  - Architecture
  - Dependency matrix
  - remove KW vs OPA Gatekeeper (move to Explanations)
  - Thread model
  - OCI registry support
  - Policy Specification
  - remove Operator Manual (move to How-to -> Operators)
  - remove Rancher UI Extension (move to How-to)
  - remove Airgap (move to Getting Started -> Installation)
  - remove Monitor mode (move to Howto -> Operators)
  - remove Fleet (move to HowTo -> Installation -> Fleet)
  - Custom Certificate authorities (from How-Tos)
  - Upgrade path
  - remove Policy evaluation timeout (move to Explanations -> Policy evaluation timeout)
```

**Comment by jvanz** [comment]
I would move the `Quick start` out of tutorials and merge it with `What is Kubewarden? (rename from "Introduction")`. Leaving the `What is Kuberwarden`  as the end section of the `Quick start`. But still keeping the `Tutorial` section for all the others. Just to have a very low friction  way to start learning Kubewarden.

I'm not sure if I would split `How-to guides` using personas. Sometimes I think some people do not know what exactly persona in the Kubewarden world they belong to. Or our persona does not match what they think it is. However, everybody know what problem needs to be solve. Therefore, I would remove the personas categorization. But this does not means that we should not have personas in mind while writing the docs. ;-)

Another thing that is not clear to me is the `Advance topics` section. What define an advanced topic? If I'm writing a docs about a "obscure" and "advance" policy feature. Where I put it? `How-to` or `Advanced topics`?  That's where I think Diataxis system helps to define where to put stuff. However, I don't think we need just the 4 proposed sections. Maybe is a matter of renaming it. But I would like to ensure that I understand the goal of the section.

**Comment by viccuad** [comment]
> , I would remove the personas categorization. But this does not means that we should not have personas in mind while writing the docs. ;-)

Good point, I agree with this.

**Comment by flavio** [comment]
I like @viccuad's proposal, with the twist suggested by @jvanz above :+1:

**Comment by viccuad** [comment]
From my side, I'm ok with any of the suggestions (even if I have listed my preferences) because they are an improvement of the status quo.

**Comment by jhkrug** [comment]
My first draft

---
title: Proposed layout
---

## Kubewarden

- What is Kubewarden
  - Quick start
- Tutorials
  - Writing policies
  - Testing policies
  - Publishing policies
  - Verification
  - What next?
- Explanation
  - Mutating policies
  - Context-aware policies
  - Distributing policies

    ?? Can the content for distributing policies here be incorporated into the tutorial page for publishing? This will be me not understanding the distinction between distributing and publishing of policies.

  - Comparisons
    - Kubewarden vs OPA Gatekeeper
  - Audit Scanner
    - Limitations
    - Policy reports
  - Kubewarden architecture

- How-Tos
  - Installation, upgrades and removal
    - Other installation scenarios
    - Upgrading
      - Supported upgrade paths
    - Removal
    - Dependency matrix (moved from Reference)
  - Common tasks (?? split into separate documents, maybe this should be 'Administration' in Tutorials?)
    - Find policies
    - Install and test policies
    - Using `kwctl`
    - Enforce policies
    - What next?
  - PSP Migration
  - Pod security admission
  - Secure supply chain
  - Custom certificate authorities
  - Raw policies
  - Audit scanner installation (?? Should this be here)

- Reference
  - Operator manual (from How-tos, merge with the one already here)
    - Configuring policy servers
      - Custom CAs
      - Private registries
    - Configuring policies
    - Quick start guides
      - OpenTelemetry
      - Metrics
      - Tracing
    - Air gap
      - Requirements
      - Installation
    - Metrics Reference
    - Custom Resource Definitions (CRDs)
    - Verification configuration
  - Policy specification
  - OCI Registry Support
  - Threat model
  - Rancher UI extension
    - Installation
    - Monitoring
    - Tracing
  - Monitor mode
  - Rancher Fleet
  - Policy evaluation timeout

**Comment by viccuad** [comment]
Agree on the distribution. Some comments:

> ?? Can the content for distributing policies here be incorporated into the tutorial page for publishing? This will be me not understanding the distinction between distributing and publishing of policies.

I think it's fine, and since there are steps, it feels more like a tutorial than an explanation anyways.

> Common tasks (?? split into separate documents, maybe this should be 'Administration' in Tutorials?) 

Agree, common tasks for whom? If not in tutorial, I would prefer them flat in How-Tos.

> Audit scanner installation (?? Should this be here)

I prefer it there, but could go in either. Tutorials IMHO should be for when one doesn't have any idea of what they need to know, How-Tos for when one knows what they need to do but don't know how. And I'm not sure Audit Scanner installation counts as tutorial.

> Reference

IMHO it should be flat and full of reference docs only, no steps. E.g: "Configuring policy servers", "metrics", "tracing", "airgap", "Rancher UI extension" all have steps, I feel they belong in How-Tos. If they explain a specific file or resource format, that part should be moved to "Reference" and the originating page should be made to link the new reference page.

**Comment by jvanz** [comment]
LGTM. :-)

**Comment by viccuad** [comment]
> Comparisons (?? Does this need a sub-section? Are more coming?) 

At least we will have Kyverno, maybe more. I'm ok flattening though for discoverability. Or having the subsections open by default.

LGTM :).

**Comment by jhkrug** [comment]
OK, all there now. I am closing as done. The output (https://github.com/kubewarden/docs/issues/332#issuecomment-1923873589) will be used in the new card for the actual docs code change issue.
