### ISSUE TITLE
Feature: Establish glossary and setup Kubewarden terms variable expansion

### ISSUE THREAD

**Issue by viccuad** [kubewarden/docs#394]
From https://github.com/kubewarden/docs/pull/393#discussion_r1562516046.

## Acceptance criteria

- [x] Establish a glossary as a part of the main documentation set. Also done in #396.
- [x] #396 Update docs to substitute terms exclusive to Kubewarden (such as PolicyServer, policy-server, kwctl). They should link to  their reference pages. For example, the CRD docs, a reference glossary page, etc. Example: `[[< policy-server-component >]]`
- Follow https://kubernetes.io/docs/contribute/style/style-guide for those terms that are Kubernetes resources.

**Comment by jhkrug** [comment]
#396 should be what we are looking for.

There is some Docusaurus docs at https://docusaurus.io/docs/api/docusaurus-config#preprocessor
