### ISSUE TITLE
Use the new Google analitics tracker ID

### ISSUE THREAD

**Issue by jvanz** [kubewarden/docs#403]
As mentioned in the PR  https://github.com/kubewarden/kubewarden.io/pull/223, we should update the docs site to use the new Google analytics tracker ID.  Therefore, we can have insights  of the usage of the documentation

### Acceptance criteria
- We should be able to see traffic data from the docs website in our Google analytics dashboard.

**Comment by viccuad** [comment]
Closed by @jhkrug with https://github.com/kubewarden/docs/pull/402.
