### ISSUE TITLE
Document limitations about our self-generated certs

### ISSUE THREAD

**Issue by flavio** [kubewarden/docs#421]
Currently our root CA and the internal certs generated by it have a lifetime of 10 years. We are not doing rotation of these resources yet.

We should update our docs to:

- make users aware of this temporary limitation
- explain how to force the creation of the certs/root CA. We can use the instructions provided inside of the blog post of 1.14

**Comment by jhkrug** [comment]
Hi @flavio and/or @jvanz . Regarding this. The instructions in the blog post seem ok. They can be expanded with an example. My question though is where to put this information in the docs? 

As a developer using Kubewarden, where would you expect to see this workaround documented?

In the Howtos? The Secure Supply Chain Section? Somewhere in the 'Configuring policy servers' Howto.

WDYT?

**Comment by flavio** [comment]
What about adding a new sidebar item: "Howtos/Limitations"?

**Comment by Martin-Weiss** [comment]
As we have some sort of cert-manager integration - I guess we should add the info on how to use cert-manager for this purpose as well?

**Comment by jhkrug** [comment]
I like @flavio 's idea of a new section to keep stuff like this separate. I think I want to call it 'Howtos/Work-arounds' though. It's a minor point. It;s how to work round a current limitation. If we called it limitations I think it would fit better under Explanations, but as in it we are going to explain how to work around something ...... Hmmm? Anyway, for the moment I'm going with work-arounds.

**Comment by viccuad** [comment]
@jhkrug is this complete with https://github.com/kubewarden/docs/pull/423?

**Comment by flavio** [comment]
I would say so. Closing as fixed
