### ISSUE TITLE
Document how to use OPA policies

### ISSUE THREAD

**Issue by flavio** [kubewarden/docs#47]
Explain the workflow needed to run a vanilla OPA policy on top of Kubewarden.

This should cover topics such as:

* Clarification between vanilla Opa and Gatekeeper
* How to build a `rego` file to `Wasm`
* Rego builtins:
   * We don't support all of them yet
   * What happens when a policy uses a builtin we don't support yet
* kwctl developer flow:
  * Annotate: what to put into the metadata
  * Push workflow: nothing changes, let's say that out loud
* kwctl operator flow: pull, run, scaffold: nothing changes, let's talk about that!

Also, we should provide some practical examples.

**Comment by ereslibre** [comment]
This is done and in blocking state waiting for all the features it links to to be merged and published.
