### ISSUE TITLE
Observability: explain how to use our Grafana dashboard

### ISSUE THREAD

**Issue by flavio** [kubewarden/docs#68]
Update the docs so that the following acceptance criteria are met.

## Acceptance criteria

* User knows where to find our grafana dashboard: link to the marketplace
* Explain how to access the Grafana instance created by the Prometheus operator (see @ereslibre's docs)
* Provide a screenshot of how the dashboard looks like

**Comment by jvanz** [comment]
@flavio I'm reviewing this issue and I think most of the acceptance criteria are already met my @ereslibre changes. See [here](https://github.com/ereslibre/kubewarden-docs/blob/opentelemetry/src/operator-manual/telemetry/metrics/01-quickstart.md#accessing-grafana). I'm feeling that I forgot something from our last call where we discuss this. Am I?

If I'm not missing something I would update the docs adding the screenshot and the link for the dashboard file in the Grafana.com website.

**Comment by jvanz** [comment]
I've also added some docs about how to see policy-specific metrics.

**Comment by jvanz** [comment]
https://github.com/kubewarden/docs/pull/65#issuecomment-963474673

**Comment by jvanz** [comment]
This issue is blocked because we need an e-mail address to create the Grafana.com account where we will publish the Grafana dashboard.

**Comment by kkaempf** [comment]
Unblocking :wink:
